-- MySQL Script generated by MySQL Workbench
-- Fri Jun 17 21:11:56 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema spisy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `spisy` ;

-- -----------------------------------------------------
-- Schema spisy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spisy` DEFAULT CHARACTER SET utf8 ;
USE `spisy` ;

-- -----------------------------------------------------
-- Table `spisy`.`Klienti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Klienti` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Klienti` (
  `ID_Klienti` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ICO` VARCHAR(8) NULL DEFAULT NULL,
  `Nazev` VARCHAR(35) NULL DEFAULT NULL,
  `Jmeno` VARCHAR(25) NULL DEFAULT NULL,
  `Prijmeni` VARCHAR(25) NULL DEFAULT NULL,
  `Telefon` VARCHAR(13) NULL DEFAULT NULL,
  `Email` VARCHAR(25) NULL DEFAULT NULL,
  `Ulice` VARCHAR(25) NULL DEFAULT NULL,
  `Mesto` VARCHAR(25) NULL DEFAULT NULL,
  `PSC` VARCHAR(5) NULL DEFAULT NULL,
  `Stat` VARCHAR(20) NULL DEFAULT NULL,
  `vlozil` VARCHAR(25) NOT NULL,
  `registrace` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_Klienti`),
  UNIQUE INDEX `ID_Klienti_UNIQUE` (`ID_Klienti` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spisy`.`Posta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Posta` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Posta` (
  `ID_posta` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Odesilatel` VARCHAR(45) NOT NULL,
  `Prijemce` VARCHAR(45) NOT NULL,
  `Zprava` TEXT NOT NULL,
  `vlozil` VARCHAR(25) NOT NULL,
  `registrace` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_posta`),
  UNIQUE INDEX `ID_posta_UNIQUE` (`ID_posta` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spisy`.`Spisy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Spisy` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Spisy` (
  `Spisova_znacka` INT(10) UNSIGNED NOT NULL,
  `Klient` INT(10) UNSIGNED NOT NULL,
  `Protistrana` INT(10) UNSIGNED NOT NULL,
  `Nazev_spisu` VARCHAR(45) NULL DEFAULT NULL,
  `Datum_zadani` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Taxa` INT(11) NULL DEFAULT NULL,
  `Pausal` INT(11) NULL DEFAULT NULL,
  `vlozil` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`Spisova_znacka`, `Protistrana`, `Klient`),
  UNIQUE INDEX `Spisova_znacka_UNIQUE` (`Spisova_znacka` ASC),
  INDEX `fk_Spisy_Klienti1_idx` (`Klient` ASC),
  INDEX `fk_Spisy_Klienti2_idx` (`Protistrana` ASC),
  CONSTRAINT `fk_Spisy_Klienti1`
    FOREIGN KEY (`Klient`)
    REFERENCES `spisy`.`Klienti` (`ID_Klienti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Spisy_Klienti2`
    FOREIGN KEY (`Protistrana`)
    REFERENCES `spisy`.`Klienti` (`ID_Klienti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spisy`.`Spisy_has_Posta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Spisy_has_Posta` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Spisy_has_Posta` (
  `Spisy_Spisova_znacka` INT(10) UNSIGNED NOT NULL,
  `Posta_ID_posta` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`Posta_ID_posta`, `Spisy_Spisova_znacka`),
  INDEX `fk_Spisy_has_Posta_Posta1_idx` (`Posta_ID_posta` ASC),
  INDEX `fk_Spisy_has_Posta_Spisy1_idx` (`Spisy_Spisova_znacka` ASC),
  CONSTRAINT `fk_Spisy_has_Posta_Posta1`
    FOREIGN KEY (`Posta_ID_posta`)
    REFERENCES `spisy`.`Posta` (`ID_posta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Spisy_has_Posta_Spisy1`
    FOREIGN KEY (`Spisy_Spisova_znacka`)
    REFERENCES `spisy`.`Spisy` (`Spisova_znacka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spisy`.`Zamestnanci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Zamestnanci` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Zamestnanci` (
  `ID_zamestnanci` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Jmeno` VARCHAR(25) NOT NULL,
  `Prijmeni` VARCHAR(25) NOT NULL,
  `Telefon` VARCHAR(13) NULL DEFAULT NULL,
  `Email` VARCHAR(25) NULL DEFAULT NULL,
  `username` VARCHAR(25) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `vlozil` VARCHAR(25) NOT NULL,
  `registrace` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_zamestnanci`),
  UNIQUE INDEX `ID_zamestnanci_UNIQUE` (`ID_zamestnanci` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spisy`.`Spisy_has_Zamestnanci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Spisy_has_Zamestnanci` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Spisy_has_Zamestnanci` (
  `Spisy_Spisova_znacka` INT(10) UNSIGNED NOT NULL,
  `Zamestnanci_ID_zamestnanci` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`Spisy_Spisova_znacka`, `Zamestnanci_ID_zamestnanci`),
  INDEX `fk_Spisy_has_Zamestnanci_Zamestnanci1_idx` (`Zamestnanci_ID_zamestnanci` ASC),
  INDEX `fk_Spisy_has_Zamestnanci_Spisy1_idx` (`Spisy_Spisova_znacka` ASC),
  CONSTRAINT `fk_Spisy_has_Zamestnanci_Spisy1`
    FOREIGN KEY (`Spisy_Spisova_znacka`)
    REFERENCES `spisy`.`Spisy` (`Spisova_znacka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Spisy_has_Zamestnanci_Zamestnanci1`
    FOREIGN KEY (`Zamestnanci_ID_zamestnanci`)
    REFERENCES `spisy`.`Zamestnanci` (`ID_zamestnanci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spisy`.`Ukoly`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Ukoly` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Ukoly` (
  `ID_ukoly` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Spisy_Spisova_znacka` INT(10) UNSIGNED NULL DEFAULT NULL,
  `Nazev` VARCHAR(45) NOT NULL,
  `Datum_splneni` DATE NULL DEFAULT NULL,
  `vlozil` VARCHAR(25) NOT NULL,
  `registrace` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_ukoly`),
  UNIQUE INDEX `ID_ukoly_UNIQUE` (`ID_ukoly` ASC),
  INDEX `fk_Ukoly_Spisy1_idx` (`Spisy_Spisova_znacka` ASC),
  CONSTRAINT `fk_Ukoly_Spisy1`
    FOREIGN KEY (`Spisy_Spisova_znacka`)
    REFERENCES `spisy`.`Spisy` (`Spisova_znacka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spisy`.`Ukoly_has_Zamestnanci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Ukoly_has_Zamestnanci` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Ukoly_has_Zamestnanci` (
  `Ukoly_ID_ukoly` INT(10) UNSIGNED NOT NULL,
  `Zamestnanci_ID_zamestnanci` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`Ukoly_ID_ukoly`, `Zamestnanci_ID_zamestnanci`),
  INDEX `fk_Ukoly_has_Zamestnanci_Zamestnanci1_idx` (`Zamestnanci_ID_zamestnanci` ASC),
  INDEX `fk_Ukoly_has_Zamestnanci_Ukoly1_idx` (`Ukoly_ID_ukoly` ASC),
  CONSTRAINT `fk_Ukoly_has_Zamestnanci_Ukoly1`
    FOREIGN KEY (`Ukoly_ID_ukoly`)
    REFERENCES `spisy`.`Ukoly` (`ID_ukoly`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ukoly_has_Zamestnanci_Zamestnanci1`
    FOREIGN KEY (`Zamestnanci_ID_zamestnanci`)
    REFERENCES `spisy`.`Zamestnanci` (`ID_zamestnanci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spisy`.`Ukony`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Ukony` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Ukony` (
  `ID_ukony` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `Spisy_Spisova_znacka` INT(10) UNSIGNED NULL DEFAULT NULL,
  `Nazev` VARCHAR(45) NOT NULL,
  `Doba` VARCHAR(45) NOT NULL,
  `vlozil` VARCHAR(25) NOT NULL,
  `registrace` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID_ukony`),
  UNIQUE INDEX `ID_ukony_UNIQUE` (`ID_ukony` ASC),
  INDEX `fk_Ukony_Spisy_idx` (`Spisy_Spisova_znacka` ASC),
  CONSTRAINT `fk_Ukony_Spisy`
    FOREIGN KEY (`Spisy_Spisova_znacka`)
    REFERENCES `spisy`.`Spisy` (`Spisova_znacka`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `spisy`.`Ukony_has_Zamestnanci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Ukony_has_Zamestnanci` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Ukony_has_Zamestnanci` (
  `Ukony_ID_ukony` INT(10) UNSIGNED NOT NULL,
  `Zamestnanci_ID_zamestnanci` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`Ukony_ID_ukony`, `Zamestnanci_ID_zamestnanci`),
  INDEX `fk_Ukony_has_Zamestnanci_Zamestnanci1_idx` (`Zamestnanci_ID_zamestnanci` ASC),
  CONSTRAINT `fk_Ukony_has_Zamestnanci_Ukony1`
    FOREIGN KEY (`Ukony_ID_ukony`)
    REFERENCES `spisy`.`Ukony` (`ID_ukony`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ukony_has_Zamestnanci_Zamestnanci1`
    FOREIGN KEY (`Zamestnanci_ID_zamestnanci`)
    REFERENCES `spisy`.`Zamestnanci` (`ID_zamestnanci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
