-- MySQL Script generated by MySQL Workbench
-- 06/14/16 17:42:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spisy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `spisy` ;

-- -----------------------------------------------------
-- Schema spisy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spisy` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `spisy` ;

-- -----------------------------------------------------
-- Table `spisy`.`Klienti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Klienti` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Klienti` (
  `ID_Klienti` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `ICO` VARCHAR(8) NULL COMMENT '',
  `Nazev` VARCHAR(35) NULL COMMENT '',
  `Jmeno` VARCHAR(25) NULL COMMENT '',
  `Prijmeni` VARCHAR(25) NULL COMMENT '',
  `Telefon` VARCHAR(13) NULL COMMENT '',
  `Email` VARCHAR(25) NULL COMMENT '',
  `Ulice` VARCHAR(25) NULL COMMENT '',
  `Mesto` VARCHAR(25) NULL COMMENT '',
  `PSC` VARCHAR(5) NULL COMMENT '',
  `Stat` VARCHAR(20) NULL COMMENT '',
  `vlozil` VARCHAR(25) NOT NULL COMMENT '',
  `registrace` timestamp DEFAULT NOW() NOT NULL COMMENT '',  
  PRIMARY KEY (`ID_Klienti`)  COMMENT '',
  UNIQUE INDEX `ID_Klienti_UNIQUE` (`ID_Klienti` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spisy`.`Spisy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Spisy` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Spisy` (
  `Spisova_znacka` INT UNSIGNED NOT NULL COMMENT '',
  `Klient` INT UNSIGNED NOT NULL COMMENT '',
  `Protistrana` INT UNSIGNED NOT NULL COMMENT '',
  `Nazev_spisu` VARCHAR(45) NULL COMMENT '',
  `Datum_zadani` timestamp DEFAULT NOW() NOT NULL COMMENT '',
  `Taxa` INT NULL COMMENT '',
  `Pausal` INT NULL COMMENT '',
  `vlozil` varchar(25) not null,
  PRIMARY KEY (`Spisova_znacka`, `Protistrana`, `Klient`)  COMMENT '',
  UNIQUE INDEX `Spisova_znacka_UNIQUE` (`Spisova_znacka` ASC)  COMMENT '',
  INDEX `fk_Spisy_Klienti1_idx` (`Klient` ASC)  COMMENT '',
  INDEX `fk_Spisy_Klienti2_idx` (`Protistrana` ASC)  COMMENT '',
  CONSTRAINT `fk_Spisy_Klienti1`
    FOREIGN KEY (`Klient`)
    REFERENCES `spisy`.`Klienti` (`ID_Klienti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Spisy_Klienti2`
    FOREIGN KEY (`Protistrana`)
    REFERENCES `spisy`.`Klienti` (`ID_Klienti`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `spisy`.`Posta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Posta` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Posta` (
  `ID_posta` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `Odesilatel` VARCHAR(45) NOT NULL COMMENT '',
  `Prijemce` VARCHAR(45) NOT NULL COMMENT '',
  `Zprava` TEXT(1000) NOT NULL COMMENT '',
  `vlozil` VARCHAR(25) NOT NULL COMMENT '',
  `registrace` timestamp DEFAULT NOW() NOT NULL COMMENT '',
  PRIMARY KEY (`ID_posta`)  COMMENT '',
  UNIQUE INDEX `ID_posta_UNIQUE` (`ID_posta` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spisy`.`Ukony`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Ukony` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Ukony` (
  `ID_ukony` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `Spisy_Spisova_znacka` INT UNSIGNED NULL COMMENT '',
  `Nazev` VARCHAR(45) NOT NULL COMMENT '',
  `Doba` VARCHAR(45) NOT NULL COMMENT '',
  `vlozil` VARCHAR(25) NOT NULL COMMENT '',
  `registrace` timestamp DEFAULT NOW() NOT NULL COMMENT '',  
  PRIMARY KEY (`ID_ukony`)  COMMENT '',
  UNIQUE INDEX `ID_ukony_UNIQUE` (`ID_ukony` ASC)  COMMENT '',
  INDEX `fk_Ukony_Spisy_idx` (`Spisy_Spisova_znacka` ASC)  COMMENT '',
  CONSTRAINT `fk_Ukony_Spisy`
    FOREIGN KEY (`Spisy_Spisova_znacka`)
    REFERENCES `spisy`.`Spisy` (`Spisova_znacka`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spisy`.`Spisy_has_Posta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Spisy_has_Posta` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Spisy_has_Posta` (
  `Spisy_Spisova_znacka` INT UNSIGNED NOT NULL COMMENT '',
  `Posta_ID_posta` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`Posta_ID_posta`, `Spisy_Spisova_znacka`)  COMMENT '',
  INDEX `fk_Spisy_has_Posta_Posta1_idx` (`Posta_ID_posta` ASC)  COMMENT '',
  INDEX `fk_Spisy_has_Posta_Spisy1_idx` (`Spisy_Spisova_znacka` ASC)  COMMENT '',
  CONSTRAINT `fk_Spisy_has_Posta_Spisy1`
    FOREIGN KEY (`Spisy_Spisova_znacka`)
    REFERENCES `spisy`.`Spisy` (`Spisova_znacka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Spisy_has_Posta_Posta1`
    FOREIGN KEY (`Posta_ID_posta`)
    REFERENCES `spisy`.`Posta` (`ID_posta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spisy`.`Zamestnanci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Zamestnanci` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Zamestnanci` (
  `ID_zamestnanci` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `Jmeno` VARCHAR(25) NOT NULL COMMENT '',
  `Prijmeni` VARCHAR(25) NOT NULL COMMENT '',
  `Telefon` VARCHAR(13) NULL COMMENT '',
  `Email` VARCHAR(25) NULL COMMENT '',
  `username` VARCHAR(25) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',  
  `vlozil` VARCHAR(25) NOT NULL COMMENT '',
  `registrace` timestamp DEFAULT NOW() NOT NULL COMMENT '',
  PRIMARY KEY (`ID_zamestnanci`)  COMMENT '',
  UNIQUE INDEX `ID_zamestnanci_UNIQUE` (`ID_zamestnanci` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spisy`.`Spisy_has_Zamestnanci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Spisy_has_Zamestnanci` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Spisy_has_Zamestnanci` (
  `Spisy_Spisova_znacka` INT UNSIGNED NOT NULL COMMENT '',
  `Zamestnanci_ID_zamestnanci` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`Spisy_Spisova_znacka`, `Zamestnanci_ID_zamestnanci`)  COMMENT '',
  INDEX `fk_Spisy_has_Zamestnanci_Zamestnanci1_idx` (`Zamestnanci_ID_zamestnanci` ASC)  COMMENT '',
  INDEX `fk_Spisy_has_Zamestnanci_Spisy1_idx` (`Spisy_Spisova_znacka` ASC)  COMMENT '',
  CONSTRAINT `fk_Spisy_has_Zamestnanci_Spisy1`
    FOREIGN KEY (`Spisy_Spisova_znacka`)
    REFERENCES `spisy`.`Spisy` (`Spisova_znacka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Spisy_has_Zamestnanci_Zamestnanci1`
    FOREIGN KEY (`Zamestnanci_ID_zamestnanci`)
    REFERENCES `spisy`.`Zamestnanci` (`ID_zamestnanci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spisy`.`Ukoly`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Ukoly` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Ukoly` (
  `ID_ukoly` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `Spisy_Spisova_znacka` INT UNSIGNED NULL COMMENT '',
  `Nazev` VARCHAR(45) NOT NULL COMMENT '',
  `Datum_splneni` DATE NULL COMMENT '',
  `vlozil` VARCHAR(25) NOT NULL COMMENT '',
  `registrace` timestamp DEFAULT NOW() NOT NULL COMMENT '',  
  PRIMARY KEY (`ID_ukoly`)  COMMENT '',
  UNIQUE INDEX `ID_ukoly_UNIQUE` (`ID_ukoly` ASC)  COMMENT '',
  INDEX `fk_Ukoly_Spisy1_idx` (`Spisy_Spisova_znacka` ASC)  COMMENT '',
  CONSTRAINT `fk_Ukoly_Spisy1`
    FOREIGN KEY (`Spisy_Spisova_znacka`)
    REFERENCES `spisy`.`Spisy` (`Spisova_znacka`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spisy`.`Ukony_has_Zamestnanci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Ukony_has_Zamestnanci` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Ukony_has_Zamestnanci` (
  `Ukony_ID_ukony` INT UNSIGNED NOT NULL COMMENT '',
  `Zamestnanci_ID_zamestnanci` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`Ukony_ID_ukony`, `Zamestnanci_ID_zamestnanci`)  COMMENT '',
  INDEX `fk_Ukony_has_Zamestnanci_Zamestnanci1_idx` (`Zamestnanci_ID_zamestnanci` ASC)  COMMENT '',
  CONSTRAINT `fk_Ukony_has_Zamestnanci_Ukony1`
    FOREIGN KEY (`Ukony_ID_ukony`)
    REFERENCES `spisy`.`Ukony` (`ID_ukony`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ukony_has_Zamestnanci_Zamestnanci1`
    FOREIGN KEY (`Zamestnanci_ID_zamestnanci`)
    REFERENCES `spisy`.`Zamestnanci` (`ID_zamestnanci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spisy`.`Ukoly_has_Zamestnanci`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spisy`.`Ukoly_has_Zamestnanci` ;

CREATE TABLE IF NOT EXISTS `spisy`.`Ukoly_has_Zamestnanci` (
  `Ukoly_ID_ukoly` INT UNSIGNED NOT NULL COMMENT '',
  `Zamestnanci_ID_zamestnanci` INT UNSIGNED NOT NULL COMMENT '',
  INDEX `fk_Ukoly_has_Zamestnanci_Zamestnanci1_idx` (`Zamestnanci_ID_zamestnanci` ASC)  COMMENT '',
  INDEX `fk_Ukoly_has_Zamestnanci_Ukoly1_idx` (`Ukoly_ID_ukoly` ASC)  COMMENT '',
  PRIMARY KEY (`Ukoly_ID_ukoly`, `Zamestnanci_ID_zamestnanci`)  COMMENT '',
  CONSTRAINT `fk_Ukoly_has_Zamestnanci_Ukoly1`
    FOREIGN KEY (`Ukoly_ID_ukoly`)
    REFERENCES `spisy`.`Ukoly` (`ID_ukoly`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Ukoly_has_Zamestnanci_Zamestnanci1`
    FOREIGN KEY (`Zamestnanci_ID_zamestnanci`)
    REFERENCES `spisy`.`Zamestnanci` (`ID_zamestnanci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
